[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
autopilot = { git = "https://github.com/ThetaSinner/autopilot-rs" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
